#
# Zookeeper
#
# https://registry.hub.docker.com/u/jplock/zookeeper/
#
zk:
  image: jplock/zookeeper:3.4.6

#
# Mesos
#
# https://registry.hub.docker.com/u/redjack/mesos-master/
# http://mesos.apache.org/documentation/latest/configuration/
#
master:
  image: breerly/mesos
  command: mesos-master
  ports:
    - "5050:5050"
  links:
   - "zk:zookeeper"
  environment:
    MESOS_CLUSTER: breerly/fig-mesos
    MESOS_HOSTNAME: localdocker
    MESOS_WORK_DIR: /var/lib/mesos
    MESOS_LOG_DIR: /var/log
    MESOS_QUORUM: 1
    MESOS_ZK: zk://zookeeper:2181/mesos

slave1:
  image: breerly/mesos
  command: supervisord -n
  privileged: true
  links:
    - "zk:zookeeper"
  ports:
    - "5051:5051"
  environment:
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_HOSTNAME: localdocker
    MESOS_MASTER: zk://zookeeper:2181/mesos

slave2:
  image: breerly/mesos
  command: supervisord -n
  privileged: true
  links:
    - "zk:zookeeper"
  ports:
    - "5052:5052"
  environment:
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_HOSTNAME: localdocker
    MESOS_MASTER: zk://zookeeper:2181/mesos
    MESOS_PORT: "5052"

slave3:
  image: breerly/mesos
  command: supervisord -n
  privileged: true
  links:
    - "zk:zookeeper"
  ports:
    - "5053:5053"
  environment:
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_HOSTNAME: localdocker
    MESOS_MASTER: zk://zookeeper:2181/mesos
    MESOS_PORT: "5053"

#
# Marathon
#
# https://registry.hub.docker.com/u/thefactory/marathon/
# https://mesosphere.github.io/marathon/docs/command-line-flags.html
#
marathon:
  image: superguenter/marathon
  ports:
    - "8080:8080"
  links:
    - "zk:zookeeper"
  command: "--master zk://zookeeper:2181/mesos --zk zk://zookeeper:2181/marathon"

#
# Chronos
#
# https://registry.hub.docker.com/u/tomaskral/chronos/
#
chronos:
  image: tomaskral/chronos
  ports:
    - "4400:8080"
  links:
    - "zk:zookeeper"
  command: "--master zk://zookeeper:2181/mesos --zk_hosts zk://zookeeper:2181/mesos"

